import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "@/utils/api";

const SinglePostPage: NextPage = () => {
  const { status } = useSession();
  //start fetching posts asap
  api.post.getAll.useQuery();

  // return empty div if BOTH arent loadedm subce user tends to load faster
  if (status !== "authenticated") return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400  md:max-w-2xl">
          Post View
          {/* <div className="border-b border-slate-400 p-4">
            <AuthShowcase />
          </div> */}
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
